# Floyd Agent Architecture Reference

## Layered Prompt Architecture

The Floyd/SuperFloyd harness uses a three-layer prompt architecture.
Each layer has a single responsibility and a fixed position in the
system message stack.

### Layer 1: Protocol Kernel (compiled-in, cached)
- **Source**: `templates/protocol_kernel.md.tpl`
- **Injected as**: First system message (after optional provider prefix)
- **Cache control**: None on kernel itself — cached as part of the static prefix block
- **Contains**: Execution model, mode selector, debug gates, build gates, tool discipline, error recovery, context trust, continuity triggers
- **Invariant**: Cannot be edited or deleted by the user. Compiled into the binary.

### Layer 2: Role Template (compiled-in, cached)
- **Source**: `templates/floyd-general.md.tpl` or `templates/superfloyd-coder.md.tpl`
- **Injected as**: Second system message, WITH Anthropic `cache_control` breakpoint
- **Contains**: Agent identity, specialization, code quality gates, role-specific features (Lab, Autonomous Mode, Fetch Anti-Bot)
- **Invariant**: The cache breakpoint on this message causes providers to cache the entire static prefix (Kernel + Role) as a single block after the first request.

### Layer 3: Project Context (user-editable, cached via FLOYD.md)
- **Source**: `FLOYD.md` (or configured `initialize_as` filename) in the project root
- **Injected as**: Part of the role template's `{{.ContextFiles}}` block
- **Contains**: Project-specific commands, structure, conventions, testing, gotchas
- **Generated by**: `initialize.md.tpl` during first-run project initialization
- **Invariant**: Pure project context. No behavioral rules — those live in the kernel.

### Dynamic Context (per-request, never cached)
- **Injected as**: User message after the cache breakpoint
- **Contains**: Working directory, git status, date, `.supercache` state
- **Source**: `prompt/cache.go` → `buildDynamicContext()`
- **Also**: GLM reasoning anchor (appended as trailing system message for GLM models only)

## Message Stack Order

```
[0] Provider prefix       (system, no cache)     — optional, from provider config
[1] Protocol kernel       (system, no cache)     — firmware, always present
[2] Role template + MCP   (system, CACHED)       — identity + tools, cache breakpoint here
[3] Dynamic context       (user, no cache)       — env, date, git, supercache
[4+] Conversation history (user/assistant/tool)  — session messages
[N] GLM reasoning anchor  (system, no cache)     — GLM models only, if conversation > 2 msgs
```

## Harness-Level Determinism (Go infrastructure)

These behaviors are enforced by the Go agent loop regardless of prompt content:

- **StopWhen**: Context window pressure detection using per-step InputTokens
- **Two-phase tool compaction**: Older outputs (first 60%) → 1K tokens; recent → 7.5K tokens
- **Self-healing build checks**: `go build` runs after `.go` edits; errors injected into tool results
- **Requeue safety**: Idempotent prompt wrapping with hard stop at max requeues
- **Token budget**: Configurable USD cap with warning injection at threshold
- **GLM reasoning anchor**: Injected system message summarizing previous turn for models without native thinking persistence
